language: python
python:
- '3.6'
cache: pip
install:
- pip install -r requirements.txt
script:
- python test1.py
- python test2.py
deploy:
  provider: heroku
  api_key: b704a063-0687-4050-a585-c86c45b5c9e6
  app: Heroku-Flask
  on:
    repo: zayedshah/Heroku-Flask
